### ISSUE TITLE
Plugin doesn't register functions without eventgateway events

### ISSUE THREAD

**Issue by alexdebrie** [serverless/serverless-event-gateway-plugin#73]
If I have the following `serverless.yml`:

```yml
custom:
  eventTypes:
    user.created:
      authorizer: auth

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  auth:
    handler: handler.auth
  main:
    handler: handler.main
    events:
      - eventgateway:
          type: sync
          eventType: user.created
          path: /hello
          method: GET
```

My `auth` function is not registered since it doesn't have any `eventgateway` events. However, it is needed because it's the authorizer for the `user.created` event type.
