### ISSUE TITLE
enable CORS

### ISSUE THREAD

**Issue by mpadmaraj** [serverless/serverless-event-gateway-plugin#76]
I'm having hard time enabling CORS for my http POST endpoint. here is my function from yml file
```yml
functions:
  sendMessage:
    handler: handler.send
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /send/message
          method: POST
          cors: true
````
